[workspace]
resolver = "2"
members = [
    "ecdsa",
    "rfc6979",
]

[profile.dev]
opt-level = 2

[patch.crates-io]
# A global patch crates-io block is used to avoid duplicate dependencies
# when pulling a member crate through git
ecdsa           = { path = "./ecdsa" }
rfc6979         = { path = "./rfc6979" }
